version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_top10
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=top10
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=#Lsy505616
      - MYSQL_ADDRESS=10.18.108.87:3306
networks:
  default:
    external:
      name: wxcb0
